-- Migration: Create vetri_schools table
-- Created at: 2026-07-16

CREATE TABLE IF NOT EXISTS vetri_schools (
  id SERIAL PRIMARY KEY,
  district_id INTEGER NOT NULL REFERENCES districts(id) ON DELETE CASCADE,
  block_name TEXT NOT NULL,
  school_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for performance when querying by district_id
CREATE INDEX IF NOT EXISTS idx_vetri_schools_district_id ON vetri_schools (district_id);

-- Enable Row Level Security (RLS)
ALTER TABLE vetri_schools ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read access
CREATE POLICY "Allow public read access" ON vetri_schools
  FOR SELECT TO anon, authenticated USING (true);

-- Insert Vetri Palligal school mapping details
INSERT INTO vetri_schools (district_id, block_name, school_name) VALUES
(1, 'Andimadam', 'GHSS VILANDAI ANDIMADAM'),
(1, 'Ariyalur', 'GHSS ARIYALUR'),
(1, 'Jayankondam', 'GMHSS JAYANKONDAM'),
(1, 'T.Palur', 'GHSS T.PALUR'),
(2, 'Kattankolathur', 'GBHSS NANDHIVARAM'),
(2, 'Kattankolathur', 'GGHSS, CHENGALPATTU'),
(2, 'Lathur', 'GGHSS CHEYYUR'),
(2, 'Lathur', 'GHSS KOOVZTHUR'),
(2, 'Madurantagam', 'GHSS KARUNKUZHI'),
(2, 'Madurantagam', 'H.S.S.G.G.H.S.S.Madhuranthakam'),
(2, 'St.Thomas Mount', 'MMA GHSS PALLAVARAM'),
(2, 'Thiruporur', 'GBHSS THIRUPORUR'),
(2, 'Thiruporur', 'GHSS KELAMBAKKAM'),
(3, 'Adyar', 'GHSS PERUNGUDI'),
(3, 'Anna Nagar', 'GOVERNMENT MODEL HIGHER SECONDARY SCHOOL'),
(3, 'Kodambakkam', 'GHSS MGR NAGAR'),
(3, 'Royapuram South', 'Govt. Muslim Higher Secondary School'),
(3, 'Teynampet', 'GMHSS, TRIPLICANE CHENNAI-05'),
(3, 'Thiru Vi Ka Nagar', 'GMHSS GKM COLONY'),
(3, 'Thiruvotriyur', 'JGGGHSS THIRUVOTRIYUR (JEYAGOPAL GARODIYA)'),
(3, 'Tondiarpet', 'GHSS MKB NAGAR'),
(4, 'Coimbatore city', 'CCMA GGHSS RAJA STREET COIMBATORE'),
(4, 'Coimbatore city', 'CHSS RS Puram'),
(4, 'Karamadai', 'GHSS METTUPALAYAM'),
(4, 'Kinathukkadavu', 'GHSS KINATHUKADAVU'),
(4, 'Periyanaickan
Palayam', 'GHSS(MODEL) ASOKAPURAM'),
(4, 'Pollachi south', 'MPL Girls HSS'),
(4, 'Pollachi south', 'MUNICIPAL (B)HSS POLLACHI'),
(4, 'Sarkar Samakkulam', 'GHSS SS KULAM'),
(4, 'Sulur', 'GBHSS Sulur'),
(4, 'Sulur', 'GGHSS SULUR'),
(4, 'Thondamuthur', 'GBHSS THONDAMUTHUR'),
(4, 'Thondamuthur', 'GGHSS Thondamuthur'),
(4, 'Valparai', 'GHSS VALPARAI'),
(5, 'Bhuvanagiri', 'GBHSS BHUVANAGIRI'),
(5, 'Bhuvanagiri', 'GMGHSS, Bhuvanagiri'),
(5, 'Cuddalore', 'GHSS VANDIPALAYAM'),
(5, 'Kattumannarkoil', 'GBHSS KATTUMANARKOIL'),
(5, 'Kattumannarkoil', 'GGHSS, Kattumannarkoil'),
(5, 'Kumaratchi', 'ADW Nanthanar Boys School, Chidambaram'),
(5, 'Kumaratchi', 'GGHSS CHIDAMBARAM'),
(5, 'Kurinjipadi', 'GGHSS KURINJIPADI'),
(5, 'Kurinjipadi', 'GHSS, Kullanchavadi'),
(5, 'Mangalore', 'GMHSS, M. Podaiyur'),
(5, 'Panruti', 'GHSS PANRUTI'),
(5, 'Virudhachalam', 'GBHSS VIRUDHACHALAM'),
(5, 'Virudhachalam', 'GMGHSS, Virudhachalam'),
(6, 'Dharmapuri', 'AVVAIYAR GGHSS DHARMAPURI'),
(6, 'Dharmapuri', 'Adhiyaman GBHSS, Dharmapuri'),
(6, 'Harur', 'GBHSS HARUR'),
(6, 'Harur', 'GGHSS, Harur'),
(6, 'Palacode', 'GBHSS PALACODU'),
(6, 'Palacode', 'GGHSS, Palacode'),
(6, 'Pappireddipatti', 'GBHSS PAPPIREDDYPATTI'),
(6, 'Pappireddipatti', 'GGHSS, Pappireddipatti'),
(6, 'Pennagaram', 'GBHSS, Pennagaram'),
(6, 'Pennagaram', 'GGHSS PENNAGARAM'),
(7, 'Athoor', 'GHSS, N.PANJAMPATTI'),
(7, 'DINDIGUL', 'GHSS PALANI ROAD - DINDIGUL'),
(7, 'Natham', 'Duraikamalam GMHSS Naththam'),
(7, 'Natham', 'GGHSS, Natham'),
(7, 'Nilakottai', 'GHSS Nilakkottai'),
(7, 'Oddanchathram', 'KRGMHSS Oddanchatram'),
(7, 'Palani - Rural', 'GGHSS Palani'),
(7, 'Palani - Rural', 'Municipal Boys HSS, Palani'),
(7, 'Vedasandur', 'GBHSS VEDASANDUR'),
(7, 'Vedasandur', 'GGHSS, Vedasandur'),
(8, 'Anthiyur', 'GBHSS, ANTHIYUR'),
(8, 'Anthiyur', 'GGHSS ANTHIYUR'),
(8, 'Bhavani', 'GBHSS, BHAVANI'),
(8, 'Bhavani', 'GGHSS BHAVANI CENTRE 1 (FINAL)'),
(8, 'Bhavani sagar', 'KOM GGHSS P.PULIYAMPATTI'),
(8, 'Bhavani sagar', 'KVK GBHSS, P.PULIAMPATTI'),
(8, 'Erode', 'CHSS, RAILWAY COLONY'),
(8, 'Erode', 'GHSS (MODEL) ERODE(GTS)'),
(8, 'Gobi', 'MGHSS, GOBI'),
(8, 'Gobi', 'MUNICIPAL BOYS HSS GOBICHETTIPALAYAM'),
(8, 'Modakurichi', 'GBHSS, MODAKKURICHI'),
(8, 'Modakurichi', 'GGHSS MODAKKURICHI
CENTRE 1 (FINAL)'),
(8, 'Nambiyur', 'GBHSS NAMBIYUR'),
(8, 'Nambiyur', 'GGHSS, NAMBIYUR'),
(8, 'Perundurai', 'GBHSS PERUNDURAI'),
(8, 'Perundurai', 'GGHSS, PERUNDURAI'),
(9, 'Kallakurichi', 'GBHSS KALLAKURICHI'),
(9, 'Kallakurichi', 'GMGHSS KALLAKURICHI'),
(9, 'Rishivanthiyam', 'GHSS ARIYALUR'),
(9, 'Sankarapuram', 'GBHSS SANKARAPURAM'),
(9, 'Sankarapuram', 'GGHSS - DEVAPANDALAM'),
(9, 'Thirukoilur', 'GBHSS THIRUKOILUR'),
(9, 'Thirukoilur', 'GGHSS THIRUKOILUR'),
(9, 'Ulundurpet', 'GBHSS ULUNTHURPET'),
(9, 'Ulundurpet', 'GGHSS ULUNTHURPET'),
(10, 'Kancheepuram', 'GHSS(GIRLS) BIG KANCHIPURAM'),
(10, 'Kancheepuram', 'GOVT CMS BOYS HR SEC SCHOOL,KANCHEEPURAM'),
(10, 'Kundrathur', 'GGHSS KUNDRATHUR'),
(10, 'Kundrathur', 'GOVT BOYS HR SEC SCHOOL,KUNDRATHUR'),
(10, 'Sriperumbudur', 'GGHSS SRIPERUMPUDUR'),
(10, 'Sriperumbudur', 'J J GOVT BOYS HR SEC SCHOOL, SRIPERUMBUDUR'),
(10, 'Uthiramerur', 'GHSS THIRUPULIVANAM'),
(10, 'Walajabad', 'GGHSS WALAJABAD'),
(10, 'Walajabad', 'GOVT BOYS HR SEC SCHOOL, VALAJABAD'),
(11, 'Agastheeswaram', 'SLB GHSS NAGARKOIL'),
(11, 'Killiyoor', 'GHSS KARUNGAL'),
(11, 'Kurunthancode', 'GHSS AMMANDIVILAI'),
(11, 'Melpuram', 'GBHSS MARTHANDAM'),
(11, 'Thuckalay', 'GMHSS THUCKALAY'),
(12, 'Aravakurichi', 'GHSS MALAIKOILUR'),
(12, 'Karur', 'MUNICIPAL(B) HSS KARUR'),
(12, 'Karur', 'PMGHSS - Karur'),
(12, 'Krishnarayapuram', 'GHSS KRISHNARAYAPURAM'),
(12, 'Kulithalai', 'GBHSS-Kulithalai'),
(12, 'Kulithalai', 'GGHSS KULITHALAI'),
(13, 'Bargur', 'GBHHS Bargur'),
(13, 'Bargur', 'GGHSS BARGUR'),
(13, 'Hosur', 'GGHSS HOSUR'),
(13, 'Hosur', 'RV Boys GHSS'),
(13, 'Kelamangalam', 'GBHSS DENKANIKOTTAI'),
(13, 'Kelamangalam', 'GGHSS DENKANIKOTTAI'),
(13, 'Krishnagiri', 'GBHSS KRISHNAGIRI'),
(13, 'Krishnagiri', 'GGHSS KRISHNAGIRI'),
(13, 'THALLY', 'GHSS ANCHETTY'),
(13, 'Uthangarai', 'GBHSS UTHANGARAI'),
(13, 'Uthangarai', 'GGHSS UTHANGARAI'),
(13, 'Veppanapalli', 'GBHSS, Veppanapalli'),
(13, 'Veppanapalli', 'GGHSS, Veppanapalli'),
(14, 'Madurai East', 'GMGHSS Y OTHAKADAI'),
(14, 'Madurai North', 'GGHSS,MAHABOOBPALAYAM, MDU-16'),
(14, 'Madurai South', 'CORP EVRN GIRLS HSS, SOUTH VELI STREET'),
(14, 'Madurai West', 'Corporation Pandiyan Nedunchelian HSS'),
(14, 'Melur', 'G(G)HSS, MELUR'),
(14, 'Melur', 'Government Higher Secondary School,Thiruvathavur'),
(14, 'T.vadipatti', 'GOVT BOYS HR SEC SCHOOL, T.VADIPATTI'),
(14, 'T.vadipatti', 'Government Girls Higher Secondary School,Sholavandan'),
(14, 'Thirumangalam', 'GHSS THIRUMANGALAM'),
(14, 'Thiruparamkundra
m', 'NAVALAR SOMASUNDRA BHARATHIYAR CGHSS PAZHANGANATHAM'),
(14, 'Usilampatti', 'GHSS USILAMPATTI'),
(15, 'Kuttalam', 'GOVT MODEL HR. SEC. SCHOOL,
KUTTALAM'),
(15, 'Mayiladudurai', 'KITTAPPA MUNICIPAL HSS'),
(15, 'Sembanarkoil', 'GHSS, Akkur'),
(15, 'Sirkali', 'GHSS VAITHEESHWARANKOIL'),
(16, 'Kelvelur', 'GHSS KURUKATHI'),
(16, 'Nagapattinam', 'GHSS-SIKKAL'),
(16, 'Nagapattinam', 'MGHSS NAGAPATTINAM'),
(16, 'Thalainayar', 'VGHSS MANAKKUDI'),
(16, 'Thirumarugal', 'GHSS THIRUMARUGAL'),
(16, 'Vedaranyam', 'GGHSS AYAKKARANPULAM - 3 (CENTRE 1)'),
(16, 'Vedaranyam', 'SKS GHSS VEDARANYAM'),
(17, 'Namakkal', 'GGHSS NAMAKKAL'),
(17, 'Namakkal', 'GHSS NAMAKKAL south'),
(17, 'Pallipalayam', 'GBHSS KUMARAPALAYAM'),
(17, 'Pallipalayam', 'GGHSS Kumarapalayam'),
(17, 'Paramathi', 'GBHSS PARAMATHI'),
(17, 'Paramathi', 'GGHSS Paramathi'),
(17, 'Rasipuram', 'GHSS ANNASALAI RASIPURAM'),
(17, 'Sendamangalam', 'GBHSS Sendamangalam'),
(17, 'Sendamangalam', 'GGHSS SENDAMANGALAM'),
(17, 'Tiruchengode', 'GBHSS Tiruchengode'),
(17, 'Tiruchengode', 'GGHSS TIRUCHENGODE'),
(19, 'Alathur', 'GHSS MODEL PADALUR'),
(19, 'Perambalur', 'GHSS PERAMBALUR'),
(19, 'Veppanthattai', 'GHSS, Veppanthattai'),
(19, 'Veppur', 'GGHSS, KUNNAM'),
(19, 'Veppur', 'GHSS, Veppur'),
(20, 'Aranthangi', 'GGHSS, ARANTHANGI'),
(20, 'Aranthangi', 'GOVERNMENT MODEL HIGHER SECONDARY
SCHOOL , ARANTHANGI'),
(20, 'Gandarvakkottai', 'GBHSS GANDARAVAKOTTAI'),
(20, 'Gandarvakkottai', 'GOVERNMENT GIRLS HR SEC SCHOOL,
GANDARVAKKOTTAI'),
(20, 'Pudukkottai', 'Ranees GGHSS, Pudukkottai'),
(20, 'Pudukkottai', 'SRI BRAGATHANBAL GOVT HR SEC SCHOOL,
PUDUKKOTTAI.'),
(20, 'Thirumayam', 'GBHSS,THIRUMAYAM'),
(20, 'Thirumayam', 'GOVT.GIRLS.HR.SEC.SCHOOL,
THIRUMAYAM'),
(20, 'Thiruvarankulam', 'GBHSS ALANGUDI'),
(20, 'Thiruvarankulam', 'GGHSS ALANGUDI'),
(20, 'Viralimalai', 'GBHSS-VIRALIMALAI'),
(20, 'Viralimalai', 'GOVERNMENT GIRLS HIGHER SECONDARY
SCHOOL, VIRALIMALAI'),
(21, 'Kadaladi', 'GBHSS SAYALKUDI'),
(21, 'Kadaladi', 'GGHSS SAYALKUDI'),
(21, 'Mandapam', 'GHSS, MANDAPAM CAMP'),
(21, 'Mudukulathur', 'GHSS MUDUKULATHUR'),
(21, 'Paramakudi', 'R.S GBHSS PARAMAKUDI (COMBINED)'),
(21, 'Ramanathapuram', 'Municipal (G)HSS, Ramanathapuram'),
(21, 'Thiruvadanai', 'GBHSS Thiruvadanai'),
(21, 'Thiruvadanai', 'GGHSS, THIRUVADANAI'),
(22, 'Arakkonam', 'GBHSS ARAKKONAM'),
(22, 'Arakkonam', 'GGHSS Arakkonam'),
(22, 'Arcot', 'GGHSS ARCOT'),
(22, 'Sholingar', 'GBHSS SHOLINGAR'),
(22, 'Sholingar', 'TEM GMHSS SHOLINGUR'),
(22, 'Walaja East', 'GBHSS VANNIVEDU WALAJA'),
(22, 'Walaja East', 'GGHSS WALAJAPET'),
(22, 'Walaja West', 'GHSS , Ammur'),
(23, 'Attur', 'GBHSS ATTUR'),
(23, 'Attur', 'GHSS Thandavarayapuram'),
(23, 'Edappadi', 'GBHSS Edappadi'),
(23, 'Edappadi', 'GGHSS . Eddapaddy'),
(23, 'Gangavalli', 'GBHSS Gangavalli'),
(23, 'Gangavalli', 'GGHSS GANGAVALLI'),
(23, 'Kolathur', 'GHSS METTUR DAM'),
(23, 'Omalur', 'GHSS KARUPPUR'),
(23, 'Salem-Rural', 'GHSS MANIYANOOR'),
(23, 'Salem-Urban', 'GGHSS SALEM 1'),
(23, 'Salem-Urban', 'MBHSS FORT'),
(23, 'Sankari', 'GBHSS. SANKAGIRI'),
(23, 'Sankari', 'GGHSS SANKARI'),
(23, 'Tharamangalam', 'GGHSS THARAMANGALAM'),
(23, 'Tharamangalam', 'Government Model Higher Secondary School, Thuttampatti'),
(23, 'Veerapandi', 'MODEL SCHOOL VEERAPANDI'),
(23, 'Yercaud', 'GHSS YERCAUD'),
(24, 'Manamadurai', 'GGHSS, MANAMADURAI'),
(24, 'Manamadurai', 'GOVT HR SEC SCHOOL IDAIKATTUR'),
(24, 'Sakkottai', 'MV GHSS, KARAIKUDI'),
(24, 'Singampunari', 'GBHSS SINGAMPUNARI'),
(24, 'Singampunari', 'RM RM GOVT GIRLS HR SEC SCHOOL SINGAMPUNARI'),
(24, 'Sivagangai', 'GOVT HSS MARUTHUPANDIYAR NAGAR'),
(24, 'Thirupatur', 'A.P.GOVT.(B)HR.SEC.SCHOOL THIRUPPATHUR'),
(24, 'Thirupatur', 'NM G(G)HSS.Thiruppathur'),
(24, 'Thiruppuvanam', 'GGHSS THIRUPPUVANAM'),
(24, 'Thiruppuvanam', 'GOVT BOYS HSS THIRUPPUVANAM'),
(25, 'Alangulam', 'GHSS, Alangulam'),
(25, 'Kadayanallur', 'GBHSS, KADAYANALLUR'),
(25, 'Kadayanallur', 'GOVT (G) HR SEC SCHOOL, KADAYANALLUR'),
(25, 'Sankarankovil', 'GGHSS SANKARANKOVIL'),
(25, 'Sankarankovil', 'GOMATHI AMBAL GBHSS, SANKARANKOVIL'),
(25, 'Tenkasi', 'ICI GBHSS, TENKASI'),
(25, 'Tenkasi', 'TMT.MANJAMMAL GGHSS TENKASI'),
(25, 'Vasudevanallur', 'GHSS VASUDEVANALLUR'),
(26, 'Kumbakonam', 'VAIGOVINDASAMY NINAIVU GHSS THARASURAM'),
(26, 'Orathanadu', 'GBHSS ORATHANADU'),
(26, 'Orathanadu', 'GGHSS ORATHANADU'),
(26, 'Papanasam', 'GHSS - AYYAMPETTAI'),
(26, 'Pattukkottai', 'GOVERNMENT MODEL HIGHER SEC SCHOOL - PATTUKOTTAI'),
(26, 'Peravurani', 'GBHSS PERAVURANI'),
(26, 'Peravurani', 'GGHSS PERAVURANI (COMBINED)'),
(26, 'Thanjavur(Urban)', 'GGHSS ARANMANAIVALAGAM THANJAVUR'),
(26, 'Thiruvaiyar', 'GGHSS THIRUVAIYARU'),
(26, 'Thiruvaiyar', 'GHSS - MELATHIRUPPANTHURITHI'),
(26, 'Thiruvidaimarudhu
r', 'GGHSS NACHIYARKOIL THIRUVIDAIMARUTHUR THANJAVUR'),
(26, 'Thiruvidaimarudhur', 'GBHSS - NACHIYARKOVIL'),
(18, 'Coonoor', 'ARINGAR ANNA GHSS'),
(18, 'Gudalur', 'GHSS GUDALUR CENTER I'),
(18, 'Udhagamandalam', 'GHSS OOTY'),
(27, 'Aundipatty', 'GBHSS AUNDIPATTI'),
(27, 'Aundipatty', 'Government Girls Higher secondary school,'),
(27, 'Bodinayakanur', 'SEVENTHWARD GHSS BODI'),
(27, 'Cumbum', 'AR Girls HSS,Cumbum'),
(27, 'Cumbum', 'GHSS, KK patty'),
(27, 'Periyakulam', 'GHSS Lakshmipuram,Periyakulam'),
(27, 'Periyakulam', 'V.M.BOYS GHSS, PERIYAKULAM'),
(28, 'Kayathar', 'GHSS KAYATHAR'),
(28, 'Kovilpatti', 'GGHSS KOVILPATTI'),
(28, 'Kovilpatti', 'VOC GHSS, KOVILPATTI'),
(28, 'Ottapidaram', 'VOC GHSS OTTAPIDARAM'),
(28, 'Srivaikundam', 'AKS GIRLS HSS SRIVAIKUNDAM'),
(28, 'Srivaikundam', 'GHSS Mukkani'),
(28, 'Thiruchenthur', 'ASA GOVT BOYS HSS, TIRUCHENDUR'),
(28, 'Thiruchenthur', 'SMG GHSS THIRUCHENDUR'),
(28, 'Thoothukudi Rural', 'GHSS M.THANGAMMALPURAM'),
(28, 'Thoothukudi Urban', 'SEENA VANA GHSS THOOTHUKUDI'),
(28, 'Vilathikulam', 'GHSS VILATHIKULAM'),
(29, 'Andhanallur', 'GHSS,AYILAPETTAI,TRICHY'),
(29, 'Lalgudi', 'GHSS , LALGUDI'),
(29, 'Manapparai', 'GBHSS MANAPARAI'),
(29, 'Manapparai', 'GGHSS,Manapparai'),
(29, 'Mannachanallur', 'GMGHSS MANNACHANALLUR'),
(29, 'Mannachanallur', 'GOVT.BOYS HSC, MANNACHANALLUR'),
(29, 'Musiri', 'GBHSS,Musiri'),
(29, 'Musiri', 'GGHSS MUSIRI'),
(29, 'Thiruverumbur', 'GOVT ADW GIRLS HSS KATTUR'),
(29, 'Thuraiyur', 'GGHSS THURAIYUR'),
(29, 'Thuraiyur', 'GOVT ADW HSC SCHOOL, THURAIYUR'),
(29, 'Trichy-Urban', 'Govt Syed Murdusha Model HSS Trichy (Combined)'),
(30, 'Ambasamudram', 'A V RM V GOVT GIRLS HR SEC SCHOOL AMBASAMUDRAM'),
(30, 'Ambasamudram', 'GOVT HR SEC SCHOOL
VELLANGULI'),
(30, 'Nanguneri', 'GOVERNMENT GIRLS HR SEC SCHOOL
NANGUNERI'),
(30, 'Nanguneri', 'SANKARA REDDIYAR GBHSS NANGUNERI'),
(30, 'Palay-Rural', 'KRGHSS REDDIYARPATTI, THIRUNELVELI'),
(30, 'Palay-Urban', 'QUIDEMILLETH CHSS,MELAPALAYAM, THIRUNELVELI'),
(30, 'Radhapuram', 'NVC GHSS RADHAPURAM'),
(30, 'Tirunelveli Urban', 'GHSS TIRUNELVELI'),
(31, 'Jolarpet', 'GHSS VAKKANAMPATTI'),
(31, 'Madhanur', 'GHSS DEVALAPURAM'),
(31, 'Nattrampalli', 'GMHSS VANIYAMBADI'),
(31, 'Thirupattur', 'GBHSS THIRUPATUR'),
(31, 'Thirupattur', 'GGHSS, Madavalam'),
(32, 'Avinashi', 'GBHSS AVINASHI'),
(32, 'Avinashi', 'GGHSS.AVINASHI'),
(32, 'Dharapuram', 'GHSS DHARAPURAM'),
(32, 'Dharapuram', 'NCP MUNICIPAL BOYS HIGHER SECONDARY SCHOOL DHARAPURAM'),
(32, 'Gangayam', 'GHSS KANGAYAM'),
(32, 'Madathukulam', 'GHSS MADATHUKULAM'),
(32, 'Palladam', 'GBHSS, Palladam'),
(32, 'Palladam', 'GGHSS PALLADAM'),
(32, 'Tiruppur North', 'GHSS KUMAR NAGAR'),
(32, 'Tiruppur South', 'KSC BHSS, Tiruppur'),
(32, 'Tiruppur South', 'PALANIAMMAL MPL GHSS, TIRUPUR'),
(32, 'Udumalaipattai', 'BCGGHSS UDUMALPET'),
(33, 'Gummidipoondi', 'GBHSS GUMMIDIPOONDI'),
(33, 'Gummidipoondi', 'GGHSS, GUMMIDIPOONDI'),
(33, 'Minjur', 'GBHSS, PONNERI'),
(33, 'Minjur', 'GGHSS PONNERI'),
(33, 'Poonamallee', 'GBHSS, KAMARAJ NAGAR'),
(33, 'Poonamallee', 'GGHSS KAMARAJ NAGAR, AVADI'),
(33, 'R.K.Pet', 'GBHSS RK PET'),
(33, 'R.K.Pet', 'GOVT (G) HSS, R.K.PET'),
(33, 'Thiruvallur', 'KMN BRO MPL HSS THIRUVALLUR'),
(33, 'Thiruvallur', 'RMJ GGHSS TIRUVALLUR'),
(33, 'Tiruttani', 'GBHSS THIRUTTANI'),
(33, 'Tiruttani', 'GGHSS THIRUTTANI'),
(33, 'Villivakkam', 'GHSS SM NAGAR AVADI'),
(34, 'Arni', 'GBHSS, Arni'),
(34, 'Arni', 'GGMHSS ARNI'),
(34, 'Chengam', 'GBHSS CHENGAM'),
(34, 'Chengam', 'GGHSS Chengam'),
(34, 'Chetpet', 'GHSS - PAZHAMPET'),
(34, 'Cheyyar', 'GBHSS CHEYYAR'),
(34, 'Cheyyar', 'GMGHSS, Cheyyar'),
(34, 'Kalasapakkam', 'GGHSS - KALASAPAKKAM'),
(34, 'Kalasapakkam', 'GMBHSS, Kalasapakkam'),
(34, 'Kilpennathur', 'GBHSS, Kilpennathur'),
(34, 'Kilpennathur', 'GGHSS, KILPENNATHUR'),
(34, 'Polur', 'GBHSS, Polur'),
(34, 'Polur', 'GGHSS - POLUR'),
(34, 'Tiruvannamalai', 'Municipal MGGHSS (Model), Tiruvannamalai'),
(34, 'Tiruvannamalai', 'TNAP GHSS, Tiruvannamalai'),
(34, 'Vandavasi', 'GBHSS VANDAVASI'),
(34, 'Vandavasi', 'GGHSS, Vandavasi'),
(34, 'Vembakkam', 'GBHSS VEMBAKKAM'),
(34, 'Vembakkam', 'GGHSS, Vembakkam'),
(35, 'Mannargudi', 'GGHSS MODEL MANNARGUDI'),
(35, 'Mannargudi', 'MHSS, Co operative urban School, Mannargudi'),
(35, 'Nannilam', 'GBHSS, Nannilam'),
(35, 'Nannilam', 'GGHSS NANNILAM'),
(35, 'Thiruthuraipoondi', 'GBHSS THIRUTHURAIPOONDI'),
(35, 'Thiruthuraipoondi', 'GGHSS, Thiruthuraipoondi'),
(35, 'Thiruvarur', 'GHSS PULIVALAM'),
(35, 'Valangaiman', 'GBHSS VALANGAIMAN'),
(35, 'Valangaiman', 'GGHSS, Valangaiman'),
(36, 'Anaicut', 'GBHSS POIGAI'),
(36, 'Anaicut', 'GGHSS, Poigai'),
(36, 'Gudiyatham', 'GBHSS, Nellorepet'),
(36, 'Gudiyatham', 'GGHSS NADUPET GUDIYATHAM'),
(36, 'K.V.Kuppam', 'GBHSS K.V.KUPPAM'),
(36, 'K.V.Kuppam', 'GGHSS, K.V.Kuppam'),
(36, 'Katpadi', 'GBHSS KATPADI'),
(36, 'Katpadi', 'GGHSS, Katpadi'),
(36, 'Vellore Urban', 'GOVT MUSLIM HSS VELLORE'),
(37, 'Gingee', 'GOVERNMENT GIRLS HIGHER SECONDARY SCHOOL GINGEE'),
(37, 'Gingee', 'RDGBHSS GINGEE'),
(37, 'Koliyanur', 'GOVT MODEL GIRLS HR SEC SCHOOL, VILLUPURAM'),
(37, 'Koliyanur', 'Thiru Kamaraj Municipal Hr. Sec. School, Villupuram'),
(37, 'Mailam', 'GOVT HR SEC SCHOOL, THAZHUTHALI.'),
(37, 'Olakkur', 'MPL HSS, KAVERIPAKKAM, DINDIVANAM'),
(37, 'Thiruvennainallur', 'GGHSS THIRUVENNAINALLUR'),
(37, 'Thiruvennainallur', 'GOVERNMENT MODEL HIGHER SECONDARY SCHOOL EMAPPUR'),
(37, 'Vaanur', 'GHSS, Kiliyanur'),
(37, 'Vikaravandi', 'GHSS VIKIRAVANDI'),
(38, 'Aruppukottai', 'GHSS PALAVANATHAM'),
(38, 'Rajapalayam', 'SSG(B)HSS'),
(38, 'Rajapalayam', 'SSG(G)HSS,RAJAPALAYAM'),
(38, 'Sattur', 'GHSS Padanthal'),
(38, 'Sivakasi', 'A U MUNICIPAL HIGHER SECONDARY SCHOOL - SIVAKASI.'),
(38, 'Srivilliputhur', 'MPL TVK HSS , Srivilliputhur'),
(38, 'Thiruchuli', 'GHSS, M.REDDIAPATTI(MODEL)'),
(38, 'Virudhunagar', 'TPNM GIRLS HR SEC SCHOOL VIRUDHUNAGAR - CENTRE 1');
